development: &default
  adapter: mysql2
  database: broadband_downtime_development
  user: root
  password:

test:
  <<: *default
  database: broadband_downtime_test

production:
  <<: *default
  database: broadband_downtime_production
